[build]
  base    = ""
  publish="out/"
  command = "REACT_APP_STAGE=dev npm run build"

[context.production]
  command = "REACT_APP_STAGE=prod npm run build"

[context.deploy-preview]
  command = "REACT_APP_STAGE=dev npm run build"

[context.branch-deploy]
  command = "REACT_APP_STAGE=dev npm run build"

# Always redirect any request to our index.html
# and return the status code 200.
[[redirects]]
    from    = "/*"
    to      = "/index.html"
    status  = 200